#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-japicmp-gradle-plugin
Version  : elease.0.2.4
Release  : 4
URL      : https://github.com/melix/japicmp-gradle-plugin/archive/RELEASE_0_2_4.tar.gz
Source0  : https://github.com/melix/japicmp-gradle-plugin/archive/RELEASE_0_2_4.tar.gz
Source1  : https://plugins.gradle.org/m2/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.jar
Source2  : https://plugins.gradle.org/m2/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-japicmp-gradle-plugin-data = %{version}-%{release}
Requires: mvn-japicmp-gradle-plugin-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
= JApicmp Gradle Plugin
:japicmp-url: https://github.com/siom79/japicmp
:issues: https://github.com/melix/japicmp-gradle-plugin/issues
:gradle-url: http://gradle.org/
:plugin-version: 0.2.4

%package data
Summary: data components for the mvn-japicmp-gradle-plugin package.
Group: Data

%description data
data components for the mvn-japicmp-gradle-plugin package.


%package license
Summary: license components for the mvn-japicmp-gradle-plugin package.
Group: Default

%description license
license components for the mvn-japicmp-gradle-plugin package.


%prep
%setup -q -n japicmp-gradle-plugin-RELEASE_0_2_4

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-japicmp-gradle-plugin
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-japicmp-gradle-plugin/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.jar
/usr/share/java/.m2/repository/me/champeau/gradle/japicmp-gradle-plugin/0.2.4/japicmp-gradle-plugin-0.2.4.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-japicmp-gradle-plugin/LICENSE.txt
